CREATE TABLE "Brief" (
	"id" text PRIMARY KEY NOT NULL,
	"companyName" text NOT NULL,
	"contactPerson" text NOT NULL,
	"email" text NOT NULL,
	"phone" text,
	"socialLinks" text,
	"location" text,
	"teamSize" text,
	"fundingStage" text,
	"projectType" text NOT NULL,
	"projectNiche" text NOT NULL,
	"currentWebsite" text,
	"goals" text NOT NULL,
	"targetAudience" text NOT NULL,
	"competitors" text,
	"designPrefs" text,
	"brandGuidelines" text,
	"features" text NOT NULL,
	"integrations" text,
	"userRoles" text,
	"contentReady" text,
	"techStack" text,
	"complianceLevel" text,
	"expectedVolume" text,
	"budget" text NOT NULL,
	"deadline" text NOT NULL,
	"maintenance" text,
	"comments" text,
	"status" text DEFAULT 'New' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
